title: SARL-PLUS
description: Smart Analytics & Reinforcement Learning at PLUS University Salzburg
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://github.com/SARL-PLUS

